default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BuySell_development
  username:  rails
  password: rails
  host: localhost
  port: 5432

test:
  <<: *default
  database: BuySell_test

production:
  <<: *default
  database: BuySell_production
  username: BuySell
  password: <%= ENV["BUYSELL_DATABASE_PASSWORD"] %>
